name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.1
      - name: Build wheels
        run: python -m cibuildwheel
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build_wheels
  #   steps:
  #     - name: Download a distribution artifact
  #       uses: actions/download-artifact@v2
  #     - name: findstuff
  #       run: find .
  #     # - name: Publish distribution to PyPI
  #     #   uses: pypa/gh-action-pypi-publish@master
  #     #   with:
  #     #     user: __token__
  #     #     skip-existing: true
  #     #     password: ${{ secrets.PYPI_API_TOKEN }}
  #     #     packages-dir: ./wheelhouse/
